import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar/navbar';
import Hero from '../components/hero/hero';
import Servicios from '../components/servicios/servicios';
import Soluciones from '../components/soluciones/soluciones';
import Form from '../components/form/form';
import Steps from '../components/steps/steps';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Hero/>
      <Steps/>
      <Servicios/>
      <Soluciones/>
      <Form/>
      <footer class="bg-[#2e4765] p-4 text-center text-white text-thin">
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copyright 2021 Sorprendeme. Desarrollado por Box Custodia de Archivos S.A.

        </a>
      </footer>
    </div>
  )
}
